### ISSUE TITLE
integrate wave type classification

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/cobrawap#17]
1. calculating velocity vector field (on amplitude or phase signal)
2. detect waves via VVF or via trigger times
3. classify and label wave types
4. filter for wave types

One key issue here is how to integrate the wave type classification in the _wavefront_detection_ stage and how to combine it with the wavefront definition via trigger times.

**Comment by rgutzen** [comment]
![Stage04_Flowchart](https://user-images.githubusercontent.com/16289604/83006618-cdc02a80-a012-11ea-9165-d8bf91286592.jpg)

**Comment by gulpgiulia** [comment]
(maybe issue #17 (this one) and issue #32 could be merged)
