### ISSUE TITLE
Evaluating a field of local velocity in stage 05

### ISSUE THREAD

**Issue by araihC** [NeuralEnsemble/cobrawap#31]
A block evaluating the field of local velocity of each wave is needed in stage 05. I am working on it, a pull request will follow.

**Comment by rgutzen** [comment]
Which approach do you pursue?
I'm seeing the two possibility of using a gradient approach or using the already calculated optical flow vector field.

**Comment by rgutzen** [comment]
Meanwhile, a block for calculating local velocities by using spatial derivates has been integrated with PR #45.
Closing
