### ISSUE TITLE
Plotting output for each block

### ISSUE THREAD

**Issue by rgutzen** [NeuralEnsemble/cobrawap#7]

**Comment by gulpgiulia** [comment]
evaluate if include (for some blocks) parameters like "VIEW_ONLY" (True/False) or "PLOT_ENABLE" (True/False) that allow to skip processing or plotting if needed (rather than removing the block in the list of sequential actions to be performed)

**Comment by rgutzen** [comment]
The initial idea of this issue was adopted as a guiding principle in the development of the pipeline and the various blocks. For further discussions of e.g. using global parameter settings to only produce plots or to suppress the generation of plots, let's use specific issues/PRs regarding specific proposals. Therefore, closing this.
